### ISSUE TITLE
crash on admin auto-register, initial migration

### ISSUE THREAD

**Issue by ppsirg** [oscarmcm/django-places#17]
### DESCRIPTION
during first migration, it fails during admin module model registration, apparently it tries to load the model Place before doing the migrations and actually create table

### Trace
```
(buus) ging@ging-HP-ProDesk-400-G1-SFF:~/sonbox$ ./manage.py makemigrations
Traceback (most recent call last):
  File "./manage.py", line 24, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ging/.virtualenvs/buus/lib/python3.5/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/home/ging/.virtualenvs/buus/lib/python3.5/site-packages/django/core/management/__init__.py", line 337, in execute
    django.setup()
  File "/home/ging/.virtualenvs/buus/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/ging/.virtualenvs/buus/lib/python3.5/site-packages/django/apps/registry.py", line 116, in populate
    app_config.ready()
  File "/home/ging/.virtualenvs/buus/lib/python3.5/site-packages/django/contrib/admin/apps.py", line 23, in ready
    self.module.autodiscover()
  File "/home/ging/.virtualenvs/buus/lib/python3.5/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/ging/.virtualenvs/buus/lib/python3.5/site-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/home/ging/.virtualenvs/buus/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/ging/.virtualenvs/buus/lib/python3.5/site-packages/places/admin.py", line 3, in <module>
    from .models import Place
ImportError: cannot import name 'Place'
```

### STEPS
1. follow https://github.com/oscarmcm/django-places instructions
2. run ./manage.py makemigrations

### EXPECTED
./manage.py makemigrations do actuall migration files

### REALITY
./manage.py makemigrations fails

* Django Version: 1.11.2
* Python Version: 3.5.2 (linux, ubuntu, 64bits)
* library version: django-places==0.1 (through pip)

**Comment by oscarmcm** [comment]
Hey @ppsirg thanks for the detailed issue 👍 

you're using the wrong lib 

this is the correct
https://pypi.org/project/dj-places/

this is incorrect
https://pypi.org/project/django-places/

so, make sure you install `dj-places` version 1.1.4 or version 2.0.0

**Comment by oscarmcm** [comment]
Closing this issue due to unrelated lib error
