### ISSUE TITLE
Error when trying to set a `default` for the field

### ISSUE THREAD

**Issue by jordanmkoncz** [oscarmcm/django-places#43]
### DESCRIPTION
When I try to add a new `PlacesField` field to a model and include a `default` for the field, I get an error when trying to run `makemigrations`.

### Trace
```
Traceback (most recent call last):
  File "/app/manage.py", line 30, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/apps.py", line 24, in ready
    self.module.autodiscover()
  File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/__init__.py", line 24, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/usr/local/lib/python3.9/site-packages/django/utils/module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/app/weflex/users/admin.py", line 616, in <module>
    class PersonAdminForm(forms.ModelForm):
  File "/usr/local/lib/python3.9/site-packages/django/forms/models.py", line 253, in __new__
    fields = fields_for_model(
  File "/usr/local/lib/python3.9/site-packages/django/forms/models.py", line 175, in fields_for_model
    formfield = f.formfield(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/places/fields.py", line 63, in formfield
    return super(PlacesField, self).formfield(**defaults)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 929, in formfield
    return form_class(**defaults)
  File "/usr/local/lib/python3.9/site-packages/places/forms.py", line 20, in __init__
    kwargs['initial'] = Places(*kwargs['initial'].split(','))
TypeError: __init__() missing 2 required positional arguments: 'latitude' and 'longitude'
ERROR: 1
```

### STEPS
1. Try to add a new `PlacesField` field to a model and include a `default` for the field, for example:

```
class Person(models.Model):
    address = PlacesField(null=False, blank=True, default="")
```

2. Run the `makemigrations` command.

### EXPECTED
The migration is created successfully, and when applied, all existing records for the model will have a value of `""` (empty string) for this newly added field.

### REALITY
Running the `makemigrations` command fails with the error shown above.

* Django Version: 3.1.13
* Python Version: 3.9

### NOTES
When I don't set a default value for the field, e.g. `address = PlacesField(null=True, blank=True)`, the migration is created successfully, and when applied, all existing records for the model have a value of `"None"` (as a string) for this newly added field. This seems like a bug to end up with a DB CharField having a value of `"None"`, I would expect that either the DB value is `NULL` (i.e. `None` in Python), or that the value is an empty string.

Just to see if it would work as an alternative, I did try `address = PlacesField(null=True, blank=True, default=None)` and got essentially the same error. 

Given that `PlacesField` is using Django's `CharField` under the hood, it seems most appropriate to use an empty string to represent an empty value for the field, and to disallow a DB `NULL` value for the field (i.e. `null=False`). This means that you only need to consider an empty string when checking for an empty value for the field, avoiding the situation where an empty value can be represented by _either_ an empty string or by the DB `NULL` value, which is not ideal.

**Comment by oscarmcm** [comment]
Hey @jordanmkoncz thanks for the detailed issue report. 

Does the database already has some records?

**Comment by jordanmkoncz** [comment]
@oscarmcm no problem. Yes, I am seeing this issue happen when adding a new `PlacesField` to a model that already exists and has records. All of those existing records end up with a value of `"None"` (as a string) for this newly added field.

I am using v5.1.0 of django-places.

**Comment by jordanmkoncz** [comment]
@oscarmcm thank you for resolving this :)
